export enum LugaresViaje {
    MONTERREY ='MONTERREY',
    CANCUN = 'CANCUN',
    BUENOS_AIRES = 'BUENOS AIRES',
    BOGOTA = 'BOGOTA',
    PANAMA = 'PANAMA',
    LOS_ANGELES = 'LOS ANGELES',
    CDMX ='CDMX'
}
